name: flutterdeteksi
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
  lottie: ^2.3.2
  validators: ^3.0.0
  carousel_indicator: ^1.0.6
  carousel_slider: ^4.2.1
  page_transition: ^2.0.9
  camera: ^0.10.5
  google_mlkit_face_detection: ^0.6.0
  cached_network_image: ^3.2.3
  image_picker: ^0.8.7+4
  flutter_otp_text_field: ^1.1.1
  sqflite: ^2.2.8+4
  sqflite_common_ffi_web: ^0.3.5+1
  flutter_toggle_tab: ^1.3.0
  flutter_dialogs: ^3.0.0
  http: ^0.13.4
  hive_flutter: ^1.1.0
  mongo_dart: ^0.9.1
  get: 4.6.5
  flutter:
    sdk: flutter
  intl: ^0.18.1
  flutter_inappwebview: ^5.7.2+3
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
  uses-material-design: true
